#if LINUX
using BPUtil;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Text;

namespace KVStore
{
	/// <summary>
	/// <para>Writes a systemd drop-in file that sandboxes the service.  BPUtil generates the service's unit file, so the hardening directives are added in a drop-in (<c>/etc/systemd/system/&lt;service&gt;.service.d/hardening.conf</c>) rather than by editing the unit.</para>
	/// </summary>
	public static class LinuxSystemdHardening
	{
		private static string GetDropInDirectory(string serviceName)
		{
			return "/etc/systemd/system/" + serviceName + ".service.d";
		}
		/// <summary>
		/// Returns the drop-in file content.
		/// </summary>
		/// <returns></returns>
		public static string GetDropInContent()
		{
			string writableDir = Globals.WritableDirectoryBase.TrimEnd('/');
			string appDir = Globals.ApplicationDirectoryBase.TrimEnd('/');
			StringBuilder sb = new StringBuilder();
			sb.Append("# Generated by KVStore.  Re-generated each time the \"install\" command is run.\n");
			sb.Append("[Service]\n");
			sb.Append("NoNewPrivileges=yes\n");
			sb.Append("PrivateTmp=yes\n");
			sb.Append("ProtectSystem=strict\n");
			if (IsUnder(appDir, "/home") || IsUnder(appDir, "/root") || IsUnder(appDir, "/run/user"))
			{
				// The program files are in a home directory (the installer's default), so the home directories are replaced with an empty tmpfs and only the program directory is made visible, read-only.
				sb.Append("ProtectHome=tmpfs\n");
				sb.Append("BindReadOnlyPaths=" + appDir + "\n");
			}
			else
				sb.Append("ProtectHome=yes\n");
			// The settings file, logs, certificate, database, and stored values all live in the writable directory.
			sb.Append("ReadWritePaths=" + writableDir + "\n");
			// AF_NETLINK is required by .NET to enumerate network interfaces, which BPUtil's web server does at startup.
			sb.Append("RestrictAddressFamilies=AF_INET AF_INET6 AF_UNIX AF_NETLINK\n");
			return sb.ToString();
		}
		private static bool IsUnder(string path, string dir)
		{
			return path == dir || path.StartsWith(dir + "/", StringComparison.Ordinal);
		}
		/// <summary>
		/// Writes the drop-in file and reloads systemd.  Writes console output explaining the result.
		/// </summary>
		/// <param name="serviceName">Name of the systemd service.</param>
		public static void Apply(string serviceName)
		{
			try
			{
				string dir = GetDropInDirectory(serviceName);
				Directory.CreateDirectory(dir);
				string path = Path.Combine(dir, "hardening.conf");
				File.WriteAllText(path, GetDropInContent(), ByteUtil.Utf8NoBOM);
				RunSystemctl("daemon-reload");
				EConsole.I.GreenLine("Wrote systemd sandboxing directives to " + path);
			}
			catch (Exception ex)
			{
				EConsole.I.RedLine("Unable to write the systemd hardening drop-in: " + ex.FlattenMessages());
			}
		}
		/// <summary>
		/// Deletes the drop-in file and reloads systemd.
		/// </summary>
		/// <param name="serviceName">Name of the systemd service.</param>
		public static void Remove(string serviceName)
		{
			try
			{
				string dir = GetDropInDirectory(serviceName);
				string path = Path.Combine(dir, "hardening.conf");
				if (File.Exists(path))
					File.Delete(path);
				if (Directory.Exists(dir) && !Directory.EnumerateFileSystemEntries(dir).Any())
					Directory.Delete(dir);
				RunSystemctl("daemon-reload");
			}
			catch (Exception ex)
			{
				EConsole.I.RedLine("Unable to remove the systemd hardening drop-in: " + ex.FlattenMessages());
			}
		}
		private static void RunSystemctl(string args)
		{
			using (Process p = Process.Start(new ProcessStartInfo("systemctl", args) { UseShellExecute = false }))
				p?.WaitForExit(30000);
		}
	}
}
#endif
